//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
typedef struct SvrCh_DINT 
  {
    CHMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrCh_DINT;

typedef struct CltCh_DINT 
  {
    struct SvrCh_DINT *pCh;
    DINT dData;
    SVRCHCMD *pCmd;
  } CltCh_DINT;

typedef struct SvrCh_HDINT 
  {
    CHMETH *pMeth;
    HDINT dData;
    SVRDSC *pDsc;
  } SvrCh_HDINT;

typedef struct CltCh_HDINT 
  {
    struct SvrCh_HDINT *pCh;
    HDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_HDINT;

typedef struct SvrCh_UDINT 
  {
    CHMETH *pMeth;
    UDINT dData;
    SVRDSC *pDsc;
  } SvrCh_UDINT;

typedef struct CltCh_UDINT 
  {
    struct SvrCh_UDINT *pCh;
    UDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_UDINT;

typedef struct SvrChCmd_DINT 
  {
    CMDMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_DINT;

typedef struct CltChCmd__FileSys 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _FileSys *pCmd;
  } CltChCmd__FileSys;

typedef struct CltChCmd__Lse 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Lse *pCmd;
  } CltChCmd__Lse;

typedef struct CltChCmd__MultiTask 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _MultiTask *pCmd;
  } CltChCmd__MultiTask;

typedef struct SvrChCmd_EState_t_PTofCls_CAssert 
  {
    CMDMETH *pMeth;
    EState_t dData;
    SVRDSC *pDsc;
  } SvrChCmd_EState_t_PTofCls_CAssert;

typedef struct CltChCmd_CAssert 
  {
    struct SvrChCmd_EState_t_PTofCls_CAssert *pCh;
    EState_t dData;
    CAssert *pCmd;
  } CltChCmd_CAssert;

typedef struct CltChCmd_CCoverageInfo 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    CCoverageInfo *pCmd;
  } CltChCmd_CCoverageInfo;

typedef struct CltChCmd_CJUnitReport 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    CJUnitReport *pCmd;
  } CltChCmd_CJUnitReport;

typedef struct CltChCmd_CLinkedList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    CLinkedList *pCmd;
  } CltChCmd_CLinkedList;

typedef struct CltChCmd_CScreenInterface 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    CScreenInterface *pCmd;
  } CltChCmd_CScreenInterface;

typedef struct CltChCmd_CTestReportBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    CTestReportBase *pCmd;
  } CltChCmd_CTestReportBase;

typedef struct SvrChCmd_EState_t_PTofCls_CTestSuite 
  {
    CMDMETH *pMeth;
    EState_t dData;
    SVRDSC *pDsc;
  } SvrChCmd_EState_t_PTofCls_CTestSuite;

typedef struct CltChCmd_CTestSuite 
  {
    struct SvrChCmd_EState_t_PTofCls_CTestSuite *pCh;
    EState_t dData;
    CTestSuite *pCmd;
  } CltChCmd_CTestSuite;

typedef struct CltChCmd_DataServiceClient 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DataServiceClient *pCmd;
  } CltChCmd_DataServiceClient;

typedef struct CltChCmd_DINT 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SVRCHCMD *pCmd;
  } CltChCmd_DINT;

typedef struct CltChCmd_GetBroadCastData 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    GetBroadCastData *pCmd;
  } CltChCmd_GetBroadCastData;

typedef struct CltChCmd_Graphic 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Graphic *pCmd;
  } CltChCmd_Graphic;

typedef struct SvrChCmd_UDINT 
  {
    CMDMETH *pMeth;
    UDINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_UDINT;

typedef struct CltChCmd_MerkerEx 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    MerkerEx *pCmd;
  } CltChCmd_MerkerEx;

typedef struct CltChCmd_Ram 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Ram *pCmd;
  } CltChCmd_Ram;

typedef struct CltChCmd_RAMex 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    RAMex *pCmd;
  } CltChCmd_RAMex;

typedef struct CltChCmd_SigCLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SigCLib *pCmd;
  } CltChCmd_SigCLib;

typedef struct CltChCmd_String 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    String *pCmd;
  } CltChCmd_String;

typedef struct CltChCmd_StringInternal 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    StringInternal *pCmd;
  } CltChCmd_StringInternal;

typedef struct CltChCmd_StringRAM 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    StringRAM *pCmd;
  } CltChCmd_StringRAM;

typedef struct CltChCmd_System 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    System *pCmd;
  } CltChCmd_System;

typedef struct SvrCh_ECommand_t_PTofCls_CTestLib 
  {
    CHMETH *pMeth;
    ECommand_t dData;
    SVRDSC *pDsc;
  } SvrCh_ECommand_t_PTofCls_CTestLib;

typedef struct SvrCh_TIME_LSL 
  {
    CHMETH *pMeth;
    TIME_LSL dData;
    SVRDSC *pDsc;
  } SvrCh_TIME_LSL;

typedef struct SvrCh_TIMEZONE_LSL_PTofCls__SysDateTime 
  {
    CHMETH *pMeth;
    TIMEZONE_LSL dData;
    SVRDSC *pDsc;
  } SvrCh_TIMEZONE_LSL_PTofCls__SysDateTime;

typedef struct SvrChCmd_BDINT 
  {
    CMDMETH *pMeth;
    BDINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_BDINT;

typedef struct SvrChCmd_DATE_LSL 
  {
    CMDMETH *pMeth;
    DATE_LSL dData;
    SVRDSC *pDsc;
  } SvrChCmd_DATE_LSL;

typedef struct SvrChCmd_EState_t_PTofCls_CTestLib 
  {
    CMDMETH *pMeth;
    EState_t dData;
    SVRDSC *pDsc;
  } SvrChCmd_EState_t_PTofCls_CTestLib;

typedef struct SvrChCmd_ETestState_t_PTofCls_CTestBase 
  {
    CMDMETH *pMeth;
    ETestState_t dData;
    SVRDSC *pDsc;
  } SvrChCmd_ETestState_t_PTofCls_CTestBase;

