//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
#pragma pack(push, 1)
typedef struct _BasicCanObj 
  {
    USINT CanData [7+1-0];
    USINT length;  //! <Type Comment="datalength of object" Name="_BasicCanObj.length"/>
    UDINT objnumber;  //! <Type Comment="objectnumber" Name="_BasicCanObj.objnumber"/>
  } _BasicCanObj;
#pragma pack(pop)

typedef USINT *_PVOIDL;

