//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
TYPE
  SvrCh_DINT : STRUCT
    pMeth : ^CHMETH;
    dData : DINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_DINT : STRUCT
    pCh : ^SvrCh_DINT;
    dData : DINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_HDINT : STRUCT
    pMeth : ^CHMETH;
    dData : HDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_HDINT : STRUCT
    pCh : ^SvrCh_HDINT;
    dData : HDINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_UDINT : STRUCT
    pMeth : ^CHMETH;
    dData : UDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_UDINT : STRUCT
    pCh : ^SvrCh_UDINT;
    dData : UDINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrChCmd_DINT : STRUCT
    pMeth : ^CMDMETH;
    dData : DINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__FileSys : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_FileSys;
  END_STRUCT;
  CltChCmd__Lse : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_Lse;
  END_STRUCT;
  CltChCmd__MultiTask : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_MultiTask;
  END_STRUCT;
  SvrChCmd_EState_t_PTofCls_CAssert : STRUCT
    pMeth : ^CMDMETH;
    dData : CAssert::EState_t;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd_CAssert : STRUCT
    pCh : ^SvrChCmd_EState_t_PTofCls_CAssert;
    dData : CAssert::EState_t;
    pCmd : ^CAssert;
  END_STRUCT;
  CltChCmd_CCoverageInfo : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^CCoverageInfo;
  END_STRUCT;
  CltChCmd_CJUnitReport : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^CJUnitReport;
  END_STRUCT;
  CltChCmd_CLinkedList : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^CLinkedList;
  END_STRUCT;
  CltChCmd_CScreenInterface : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^CScreenInterface;
  END_STRUCT;
  CltChCmd_CTestReportBase : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^CTestReportBase;
  END_STRUCT;
  SvrChCmd_EState_t_PTofCls_CTestSuite : STRUCT
    pMeth : ^CMDMETH;
    dData : CTestSuite::EState_t;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd_CTestSuite : STRUCT
    pCh : ^SvrChCmd_EState_t_PTofCls_CTestSuite;
    dData : CTestSuite::EState_t;
    pCmd : ^CTestSuite;
  END_STRUCT;
  CltChCmd_DataServiceClient : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^DataServiceClient;
  END_STRUCT;
  CltChCmd_DINT : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  CltChCmd_GetBroadCastData : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^GetBroadCastData;
  END_STRUCT;
  CltChCmd_Graphic : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Graphic;
  END_STRUCT;
  SvrChCmd_UDINT : STRUCT
    pMeth : ^CMDMETH;
    dData : UDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd_MerkerEx : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^MerkerEx;
  END_STRUCT;
  CltChCmd_Ram : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Ram;
  END_STRUCT;
  CltChCmd_RAMex : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^RAMex;
  END_STRUCT;
  CltChCmd_SigCLib : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SigCLib;
  END_STRUCT;
  CltChCmd_String : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^String;
  END_STRUCT;
  CltChCmd_StringInternal : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^StringInternal;
  END_STRUCT;
  CltChCmd_StringRAM : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^StringRAM;
  END_STRUCT;
  CltChCmd_System : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^System;
  END_STRUCT;
  SvrCh_ECommand_t_PTofCls_CTestLib : STRUCT
    pMeth : ^CHMETH;
    dData : CTestLib::ECommand_t;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_TIME_LSL : STRUCT
    pMeth : ^CHMETH;
    dData : TIME_LSL;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_TIMEZONE_LSL_PTofCls__SysDateTime : STRUCT
    pMeth : ^CHMETH;
    dData : _SysDateTime::TIMEZONE_LSL;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrChCmd_BDINT : STRUCT
    pMeth : ^CMDMETH;
    dData : BDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrChCmd_DATE_LSL : STRUCT
    pMeth : ^CMDMETH;
    dData : DATE_LSL;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrChCmd_EState_t_PTofCls_CTestLib : STRUCT
    pMeth : ^CMDMETH;
    dData : CTestLib::EState_t;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrChCmd_ETestState_t_PTofCls_CTestBase : STRUCT
    pMeth : ^CMDMETH;
    dData : CTestBase::ETestState_t;
    pDsc : ^SVRDSC;
  END_STRUCT;
END_TYPE
