//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
#define  ALIGNMENT 4
#include <Class.h>
#include <RTOS_Globals.h>
#include <RTOS_Variables.h>
#include <RTOS_PRIVATE.h>
#include <RTOS_header.h>
#include <RTOS_PRIVDefs.H>
#include <RTOS_Scan.h>

#include <Lsl_String.h>

//Linked Library Headerfiles
#include <.\File_IOTypes.h>
#include "$LIBRARYPATH(System).\Source\cppcode\T_color.h"
#include "$LIBRARYPATH(System).\Source\cppcode\T_nuc.h"
#include "$LIBRARYPATH(System).\Source\cppcode\T_types.h"
#include "$LIBRARYPATH(System).\Source\cppcode\T_ipc.h"
#include "$LIBRARYPATH(System).\Source\cppcode\Comintfc.h"
#include "$LIBRARYPATH(System).\Source\cppcode\T_USER.H"
#include <.\MultiTaskTypes.h>
#include "$LIBRARYPATH(System).\Class\_SysDateTime\_SysDateTime.h"
#include <.\GraphicTypes.h>
#include <.\St_grconst.h>
#include <.\St_graph.h>
#include "$LIBRARYPATH(System).\Class\Ram\Ram.h"
#include "$LIBRARYPATH(System).\Class\StringInternal\StringDefs.h"
#include <.\SystemTypes.h>

//Project Headerfiles
#include "..\Class\CTestLib\Coverage.h"
#include "..\Class\CTestLib\_Version.h"

#include "unit.h"
#include "UserDef.h"
#include "types.h"
#include "lslpublictypes.h"
#include "channels.h"

#define LSL_SWAP(x)  (((x) SHL 24) OR ((x AND 16#0000ff00) SHL 8) OR((x AND 16#00ff0000) SHR 8) OR ((x) SHR 24))
#define LSL_GUID(g0,g1,g2,g3,g4) g0$DINT, g1$INT, g2$INT, LSL_SWAP(g3)$DINT, LSL_SWAP(g4)$DINT
