//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
#RE_IN_DE
#pragma define (store)
_SysDateTime : CLASS_PUBLIC
	TYPE
	  TIMEZONE_LSL :
	  (
	    tz_INACTIVE:=0,
	    tz_UTC:=1,
	    tz_Europe_Andorra:=1000,
	    tz_Europe_Athens:=1001,
	    tz_Europe_Belgrade:=1002,
	    tz_Europe_Berlin:=1003,
	    tz_Europe_Brussels:=1004,
	    tz_Europe_Bucharest:=1005,
	    tz_Europe_Budapest:=1006,
	    tz_Europe_Chisinau:=1007,
	    tz_Europe_Dublin:=1008,
	    tz_Europe_Helsinki:=1009,
	    tz_Europe_Istanbul:=1010,
	    tz_Europe_Kyiv:=1011,
	    tz_Europe_Lisbon:=1012,
	    tz_Europe_London:=1013,
	    tz_Europe_Madrid:=1014,
	    tz_Europe_Minsk:=1015,
	    tz_Europe_Moscow:=1016,
	    tz_Europe_Paris:=1017,
	    tz_Europe_Prague:=1018,
	    tz_Europe_Riga:=1019,
	    tz_Europe_Rome:=1020,
	    tz_Europe_Sofia:=1021,
	    tz_Europe_Tallinn:=1022,
	    tz_Europe_Tirane:=1023,
	    tz_Europe_Vienna:=1024,
	    tz_Europe_Vilnius:=1025,
	    tz_Europe_Warsaw:=1026,
	    tz_Europe_Zurich:=1027,
	    tz_America_Buenos_Aires:=3000,
	    tz_America_Chicago:=3001,
	    tz_America_Denver:=3002,
	    tz_America_Halifax:=3003,
	    tz_America_Lima:=3004,
	    tz_America_Los_Angeles:=3005,
	    tz_America_Manaus:=3006,
	    tz_America_Mexico_City:=3007,
	    tz_America_New_York:=3008,
	    tz_America_Santiago:=3009,
	    tz_America_Sao_Paulo:=3010,
	    tz_America_Toronto:=3011,
	    tz_America_Vancouver:=3012,
	    tz_Asia_Almaty:=4000,
	    tz_Asia_Baghdad:=4001,
	    tz_Asia_Bangkok:=4002,
	    tz_Asia_Dhaka:=4003,
	    tz_Asia_Dubai:=4004,
	    tz_Asia_Jakarta:=4005,
	    tz_Asia_Jerusalem:=4006,
	    tz_Asia_Karachi:=4007,
	    tz_Asia_Kolkata:=4008,
	    tz_Asia_Magadan:=4009,
	    tz_Asia_Manila:=4010,
	    tz_Asia_Riyadh:=4011,
	    tz_Asia_Seoul:=4012,
	    tz_Asia_Shanghai:=4013,
	    tz_Asia_Singapore:=4014,
	    tz_Asia_Tehran:=4015,
	    tz_Asia_Tokyo:=4016,
	    tz_Asia_Vladivostok:=4017,
	    tz_Asia_Yakutsk:=4018,
	    tz_Africa_Cairo:=2000,
	    tz_Africa_Casablanca:=2001,
	    tz_Africa_Johannesburg:=2002,
	    tz_Africa_Lagos:=2003,
	    tz_Africa_Monrovia:=2004,
	    tz_Africa_Nairobi:=2005,
	    tz_Africa_Tripoli:=2006,
	    tz_Africa_Tunis:=2007,
	    tz_Australia_Adelaide:=5000,
	    tz_Australia_Perth:=5001,
	    tz_Australia_Sydney:=5002,
	    tz_Pacific_Auckland:=6000
	  )$DINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
#pragma InclDefBlk CAssert
CAssert : CLASS_PUBLIC
	TYPE
	  ABuffer_t : ARRAY [0..254] OF CHAR;
	  EState_t :
	  (
	    ePassed,
	    eFailed,
	    eFailedFatal
	  )$UDINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
CLinkedList : CLASS_PUBLIC
	TYPE
	  Element_t : ^void;
#pragma pack(push, 1)
	  SEntry_t : STRUCT
	    pPrev : ^SEntry_t;
	    pElement : Element_t;
	    pNext : ^SEntry_t;
	  END_STRUCT;
#pragma pack(pop)
	  Iterator_t : ^SEntry_t;
	END_TYPE
END_CLASS;
#pragma define (restore)
#pragma InclDefBlk CTestBase
CTestBase : CLASS_PUBLIC
	TYPE
	  ABuffer_t : ARRAY [0..254] OF CHAR;
	  ETestState_t :
	  (
	    eStateIdle,
	    eStatePrepare,
	    eStateExecute,
	    eStatePassed,
	    eStateFailed,
	    eStateFailedFatal,
	    eStateError,
	    eStateSkipped
	  )$UDINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
CTestLib : CLASS_PUBLIC
	TYPE
	  ECommand_t :
	  (
	    eCmdStop,
	    eCmdRun,
	    eCmdReset,
	    eCmdCreateFile
	  )$UDINT;
	  EState_t :
	  (
	    eStateIdle,
	    eStateExecute,
	    eStateNextSuite,
	    eStateError,
	    eStateCreateJUnit,
	    eStateCreateCoverage,
	    eStateCreateReport,
	    eStateNextReport
	  )$UDINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
CTestReportBase : CLASS_PUBLIC
	TYPE
	  ERetCode_t :
	  (
	    eFailed,
	    eBusy,
	    eDone
	  )$UDINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
CTestSuite : CLASS_PUBLIC
	TYPE
	  ECount_t :
	  (
	    eAll,
	    ePassed,
	    eFailed,
	    eSkipped,
	    eErrors
	  )$UDINT;
	  EState_t :
	  (
	    eStateInit,
	    eStateIdle,
	    eStatePrepare,
	    eStateExecute,
	    eStateCleanUp,
	    eStateNextTest,
	    eStateError,
	    eStateSkipped
	  )$UDINT;
#pragma pack(push, 1)
	  SStatistic_t : STRUCT
	    udElapsedTime : UDINT;
	    NbPassed : UDINT;
	    NbFailed : UDINT;
	    NbRun : UDINT;
	    NbSkipped : UDINT;
	  END_STRUCT;
#pragma pack(pop)
	END_TYPE
END_CLASS;
#pragma define (restore)
MerkerEx : CLASS_PUBLIC
#include <.\lsl_st_mt.h>
	TYPE
	  Cmdm_udLength :
	  (
	    GET_DATA_PTR,
	    EXCHANGE_DATA_PTR,
	    SAVE_DATA_TO_RAMEXFILE
	  )$UINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
VirtualBaseInit : CLASS_PUBLIC
	TYPE
	  CmdData :
	  (
	    GET_ADD_INFO,
	    READ_DATA,
	    WRITE_DATA,
	    READ_DATA_OFF,
	    WRITE_DATA_OFF
	  )$UINT;
	END_TYPE
END_CLASS;
#pragma define (restore)

#RE_IN_DE
