//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
TYPE
#pragma pack(push, 1)
  _BasicCanObj : STRUCT
    CanData : ARRAY [0..7] OF USINT;
    length : USINT;  //! <Type Comment="datalength of object" Name="_BasicCanObj.length"/>
    objnumber : UDINT;  //! <Type Comment="objectnumber" Name="_BasicCanObj.objnumber"/>
  END_STRUCT;
#pragma pack(pop)
  _PVOIDL : ^USINT;
END_TYPE
